# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [7]:
import numpy as np
arr=np.random.randint(1,21,size=(5,5))
print(arr)
arr[:,2]=1
print(arr)

[[14  6  7  9  9]
 [ 1 15 18 17 12]
 [15 16  3 11 16]
 [ 4 17  8  7 10]
 [15 17  8  7  2]]
[[14  6  1  9  9]
 [ 1 15  1 17 12]
 [15 16  1 11 16]
 [ 4 17  1  7 10]
 [15 17  1  7  2]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [8]:
arr=np.arange(1,17,1).reshape(4,4)
print(arr)
np.fill_diagonal(arr,0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [10]:
arr=np.arange(1,37).reshape(6,6)
print(arr)
print(arr[2:5,1:4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [16]:
arr=np.random.randint(1,21,size=(5,5))
print(arr)

borderelements=np.concatenate((arr[0],arr[-1],arr[1:-1,0],arr[1:-1,-1]))
print(borderelements)

[[20  5 18 20 12]
 [15  8  1  9 10]
 [19 16 16  6 17]
 [14 20  5  2 13]
 [ 9  4 17 19 10]]
[20  5 18 20 12  9  4 17 19 10 15 19 14 10 17 13]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [13]:
arr1=np.random.randint(1,21,size=(3,4))
arr2=np.random.randint(1,21,size=(3,4))
addition=arr1+arr2
subtraction=arr1-arr2
multiplication=arr1*arr2
division=arr1/arr2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Element-wise addition:
[[25 27 30 23]
 [15  9 11  8]
 [20 32 12 28]]
Element-wise subtraction:
[[  3 -13   4 -15]
 [ -7  -7  -1  -2]
 [ -4   8   2   4]]
Element-wise multiplication:
[[154 140 221  76]
 [ 44   8  30  15]
 [ 96 240  35 192]]
Element-wise division:
[[1.27272727 0.35       1.30769231 0.21052632]
 [0.36363636 0.125      0.83333333 0.6       ]
 [0.66666667 1.66666667 1.4        1.33333333]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
arr=np.arange(1,17).reshape(4,4)
rowwisesum=np.sum(arr,axis=1)
columnwisesum=np.sum(arr,axis=0)
print(f"Row-Wise-Sum: {rowwisesum}")
print(f"Column-Wise-Sum: {columnwisesum}")



Row-Wise-Sum: [10 26 42 58]
Column-Wise-Sum: [28 32 36 40]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [22]:
arr=np.random.randint(1,21,size=(5,5))
mean=np.mean(arr)
median=np.median(arr)
standarddeviation=np.std(arr)
variance=np.var(arr)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {standarddeviation}")
print(f"Variance: {variance}")

Mean: 8.4
Median: 8.0
Standard Deviation: 4.8166378315169185
Variance: 23.200000000000003


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [ ]:
arr=np.arange(1,10).reshape(3,3)

mean=np.mean(arr)
standarddeviation=np.std(arr)
normalized_arr=(arr-mean)/standarddeviation   # Formula for Normalization
print(normalized_arr)
print(np.mean(normalized_arr)) # This should be 0 now
print(np.std(normalized_arr))  # This should be 1 now

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
0.0
1.0


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [ ]:
arr=np.random.randint(1,21,size=(3,3))
print(arr)
rowarr=np.random.randint(1,10,size=(3,))
print(rowaarr=np.random.randint(1,21,size=(3,3))
print(arr)
rowarr=np.random.randint(1,10,size=(3,))
print(rowarr)
result=arr+rowarr
print(result)rr)
result=arr+rowarr
print(result)

[[13 20 13]
 [ 2  1  6]
 [ 1  5 15]]
[4 6 7]
[[17 26 20]
 [ 6  7 13]
 [ 5 11 22]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [32]:
arr=np.random.randint(1,21,size=(4,4))
print(arr)
columnarr=np.random.randint(1,10,size=(4,))
print(columnarr)
result=arr-columnarr[:,np.newaxis]
print(result)

[[ 9 13 15 19]
 [ 6 10  2  8]
 [15  7 11  3]
 [20 10  8 14]]
[6 1 7 9]
[[ 3  7  9 13]
 [ 5  9  1  7]
 [ 8  0  4 -4]
 [11  1 -1  5]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [ ]:
matrix=np.random.randint(1,11,size=(3,3))

determinant=np.linalg.det(matrix)
inverse=np.linalg.inv(matrix)
eigen_values=np.linalg.eigvals(matrix)

print(f"Determinant: {determinant}")
print(f"Inverse:\n {inverse}")
print(f"Eigen Values: {eigen_values}")

Determinant: 283.99999999999983
Inverse:
 [[-0.1443662   0.21830986  0.08802817]
 [-0.05985915 -0.00704225  0.1584507 ]
 [ 0.24295775 -0.14788732 -0.17253521]]
Eigen Values: [17.99106394+0.j         -2.99553197+2.61005799j -2.99553197-2.61005799j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [36]:
arr1=np.random.randint(1,11,size=(2,3))
arr2=np.random.randint(1,11,size=(3,2))
result=np.dot(arr1,arr2)

print("Matrix multiplication result:")
print(result)

Matrix multiplication result:
[[ 51  68]
 [115 136]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [37]:
arr=np.arange(1,10).reshape(3,3)
print(arr)
arr=arr.reshape(1,9)
print(arr)
arr=arr.reshape(9,1)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [38]:
arr=np.random.randint(1,21,size=(5,5))
print(arr)
arr=arr.flatten()
print(arr)
arr.reshape(5,5)
print(arr)

[[13 15 16  1  5]
 [ 6 12  9  2 13]
 [19 18 18 20 14]
 [11 16  5  8 12]
 [ 3 19 16 17 11]]
[13 15 16  1  5  6 12  9  2 13 19 18 18 20 14 11 16  5  8 12  3 19 16 17
 11]
[13 15 16  1  5  6 12  9  2 13 19 18 18 20 14 11 16  5  8 12  3 19 16 17
 11]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [ ]:
arr=np.random.randint(1,21,size=(5,5))
corner=arr[[0,0,-1,-1],[0,-1,0,-1]] 
# in fancy addressing it is taken as a pair 1 fom list1 and other from2
print(corner)

[np.int32(19), np.int32(7), np.int32(6), np.int32(17)]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [8]:
arr=np.random.randint(1,21,size=(4,4))
arr[arr>10]=10
print(arr)

[[ 4 10 10  6]
 [10  4  8 10]
 [10 10 10 10]
 [10 10 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [7]:
data_types=[('name','U10'),("age","i4"),("weight","f4")]
array=np.array([("Ahmad",18,59.5),("Ali",21,67.7),("Umer",20,61.5)],dtype=data_types)
print(array)
sorted_array=np.sort(array,order="age")
print(sorted_array)

[('Ahmad', 18, 59.5) ('Ali', 21, 67.7) ('Umer', 20, 61.5)]
[('Ahmad', 18, 59.5) ('Umer', 20, 61.5) ('Ali', 21, 67.7)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [15]:
data_types=[('x','i4'),('y','i4')]
arr=np.array([(1,2),(3,4),(5,6)],dtype=data_types)
euclidean_distance=np.sqrt((arr['x'][:,np.newaxis]-arr['x'])**2+(arr['y'][:,np.newaxis]-arr['y'])**2)
print("Euclidean Distance: ",euclidean_distance)

Euclidean Distance:  [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [19]:
import numpy.ma as ma
arr=np.random.randint(1,21,size=(4,4))
print(arr)
masked_array=ma.masked_greater(arr,10)
print(masked_array)
sum_of_unmasked=masked_array.sum()
print("Sum of Unmasked Elements: ",sum_of_unmasked)

[[ 9 13 17  9]
 [11  6 20 18]
 [14 18  2 11]
 [12  7 15  9]]
[[9 -- -- 9]
 [-- 6 -- --]
 [-- -- 2 --]
 [-- 7 -- 9]]
Sum of Unmasked Elements:  42


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [21]:
arr=np.random.randint(1,21,size=(3,3))
print(arr)
masked_arr=ma.masked_array(arr,mask=np.eye(3,dtype=bool))
print(masked_arr)
masked_arr=masked_arr.filled(masked_arr.mean())
print(masked_arr)

[[ 8  3 17]
 [12  7 14]
 [ 9 15  7]]
[[-- 3 17]
 [12 -- 14]
 [9 15 --]]
[[11  3 17]
 [12 11 14]
 [ 9 15 11]]
